import localFont from "next/font/local";
import "./globals.css";
import { Figtree } from 'next/font/google'

// const orienta = localFont({
//   src: "./fonts/Orienta-Regular.ttf",
//   variable: "--font-orienta",
//   weight: "100 900",
// })

const figtree = Figtree({ 
  subsets: ['latin'],
  variable: '--font-figtree'
})

export const metadata = {
  title: "Due",
  icons: {
    icon: '../blue-duey.svg'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Due</title>
      <body
        className={`${figtree.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
